services:
    openconext_aa_api.guzzle:
        public: false
        class: GuzzleHttp\Client
        arguments:
            - [] # Client options

    openconext_aa_api.service.api:
        public: false
        class: OpenConext\AttributeAggregationApiClientBundle\Http\JsonApiClient
        arguments:
            - @openconext_aa_api.guzzle
