framework:
  assets:
    json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
  translator: { fallback: [ en ] }
  secret: "%secret%"
  form: ~
  csrf_protection: ~
  validation: { enable_attributes: true }
  default_locale: "%default_locale%"
  trusted_hosts: ~
  session:
    handler_id: "%session_handler%"
    cookie_secure: auto
    cookie_samesite: lax
  esi: false
  fragments: false
  http_method_override: true
  handle_all_throwables: true
  php_errors:
    log: true
  annotations: { enabled: false }
