framework:
  assets:
    json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
  translator: { fallback: [ en ] }
  secret: "%secret%"
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  default_locale: "%default_locale%"
  trusted_hosts: ~
  session:
    handler_id: ~
  fragments: ~
  http_method_override: true
