jms_translation:
  locales: '%locales%'
  configs:
    app:
      dirs: ['%kernel.root_dir%', '%kernel.root_dir%/../src']
      output_dir: '%kernel.root_dir%/translations'
      ignored_domains:
      excluded_names: ['*TestCase.php', '*Test.php']
      excluded_dirs: [cache, data, logs, Tests]
      extractors: []
