monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: ERROR
      passthru_level: NOTICE
      handler: syslog
    syslog:
      type:     syslog
      ident:    openconext-profile
      facility: user
