security:
  providers:
    saml-provider:
      id: OpenConext\ProfileBundle\Security\Authentication\Provider\SamlProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login_firewall:
      pattern: ^/saml/metadata

    monitor:
      pattern: ^/(info|health)$
      security: false

    saml_based:
      custom_authenticators:
        - Surfnet\SamlBundle\Security\Authentication\SamlAuthenticator
      logout:
        path: /logout

  access_control:
    - { path: ^/saml, roles: PUBLIC_ACCESS, requires_channel: https }
    - { path: ^/authentication, roles: PUBLIC_ACCESS, requires_channel: https }
    - { path: ^/, roles: ROLE_USER, requires_channel: https }
