surfnet_saml:
  hosted:
    service_provider:
      enabled: true
      assertion_consumer_route: profile.saml_consume_assertion
      public_key: '%saml_sp_publickey%'
      private_key: '%saml_sp_privatekey%'
    metadata:
      entity_id_route: profile.saml_metadata
      public_key: '%saml_metadata_publickey%'
      private_key: '%saml_metadata_privatekey%'
  remote:
    identity_provider:
      enabled: true
      entity_id: '%saml_remote_idp_entity_id%'
      sso_url: '%saml_remote_idp_sso_url%'
      certificate_file: '%saml_remote_idp_certificate_file%'
