language: php

php:
  - 7.2
  - 7.3

matrix:
  allow_failures:
  - php: 7.3

env:
  global:
    - SYMFONY_ENV=test

cache:
  directories:
    - ~/.composer

before_script:
  - sudo apt-get install ant
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer install --prefer-dist -n -o
  - node -v
  - nvm install 14.17.3 && nvm use 14.17.3
  - npm i && npm run build

script:
  - ant

notifications:
  slack:
    secure: E4qQdlRTVgePXDCaFuWI6dITPvC/a+4wstDUd43vR4ixL948P1gMbZYjPhaSUujGs5xgCzmQqFGiM6GmRcnjFD/GLydN/RimMNkYQ+1RyG13OAdgaeGpG9NWMbVbIMxpsJa9X4PuRSBzABFexeJjvc3CeG8FPIQjp7KCK3SJWQa15r955ZvjhOzR/wiYmqrNxsg1pS71lOC50wQp/BWMBqmG1OLsutbnOsJFjPLbmigJpmNcjE9hZ+jpHJTkSIPa1qrG+h7ez9lLGODtocMy8ztVxurChh+h7LifVPyGfcrNv8URP5BEWwsdhkRFNsH+8M4NJcJ1bTrfl1w3TiGAVdAsOlp29Zj5YBTRkNtOFWscKFWoWBS19yoViR/URKuChPxZKeUOQYYVHhr/oA1mwBPEuyt1vKZiJtGz/izHEwlXYg58Gt8PoNSC+7mZK+Iy4d+HPtqQJJ1IaIv9dDtakKeGGL9a3MCXee7s4sWEa2KRMTIkCrTmNjpR8VIcsLbqAtZJKZwGc3/yb+54B46FD1qGy5xgetWgcspUU9069EPvjmVBgb7Hh4EHVYgYRybghksKtdLJwdhsuLmRbN+g7dWCCOOuLICWymCY4r3PWVhAIOq037iS6msfBdk78BKUuGpKiZDB25MrK+TPnHZ67Md5afByBUIQ9SNICWJ1XTY=

branches:
  only:
    - master
    - develop
