---

version: "3.8"

services:
  openconext:
    build:
      context: 'docker/'
      dockerfile: Dockerfiledev
      target: openconext
    extra_hosts:
      engine-api.vm.openconext.org: 127.0.0.2
      engine.vm.openconext.org: 127.0.0.1
      manage.vm.openconext.org: 127.0.0.1
    privileged: true
    networks:
      profile:
        aliases:
          - db.vm.openconext.org
          - manage.vm.openconext.org
          - engine-api.vm.openconext.org
    volumes:
      - profile_mysql:/var/lib/mysql
      - profile_mongo:/var/lib/mongo
    ports:
      - "443:443"
    expose: 
      - 3306
  php-fpm:
    build:
      context: 'docker/'
      dockerfile: Dockerfiledev
      target: profilephpfpm
    volumes:
      - .:/var/www/html/
      - type: bind
        source: /dev/log
        target: /dev/log
    environment:
      - PHPFPM_PORT=9000
    networks:
      profile:
        aliases: 
          - profile_php-fpm
  web:
    build:
      context: 'docker/'
      dockerfile: Dockerfiledev
      target: profilehttpd
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/html/
    ports: 
      - "8080:80"
    networks:
      profile:
        aliases: 
          - profile_web
  cypress:
    image: "cypress/included:8.4.0"
    depends_on:
      - openconext
    environment:
      - CYPRESS_baseUrl=https://profile.vm.openconext.org
    working_dir: /var/www/html/
    entrypoint: cypress open --project .
    volumes:
      - .:/var/www/html/
networks:
  profile:

volumes:
  profile_mysql:
  profile_mongo:
