---

version: "3.8"

services:
  openconext:
    image: "ghcr.io/openconext/openconext-containers/openconext-phpfpm-dev:latest"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHPFPM_PORT=9000
