imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

nelmio_security:
    csp:
        enforce:
            img-src:
                - self
                - 'data:'
            script-src:
                - self
                - unsafe-inline
            style-src:
                - self
                - unsafe-inline

monolog:
    handlers:
        dev:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        syslog:
            type:     syslog
            ident:    openconext-profile
            facility: user
