imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locales: [en, nl]

framework:
    translator:      { fallback: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%default_locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE
            handler: syslog
            bubble: false
        syslog:
            type:     syslog
            ident:    openconext-profile
            facility: user

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

jms_translation:
    locales: %locales%
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains:
            excluded_names: ['*TestCase.php', '*Test.php']
            excluded_dirs: [cache, data, logs, Tests]
            extractors: []
surfnet_saml:
    hosted:
        service_provider:
            enabled: true
            assertion_consumer_route: profile.saml_consume_assertion
            public_key: %saml_sp_publickey%
            private_key: %saml_sp_privatekey%
        metadata:
            entity_id_route: profile.saml_metadata
            public_key: %saml_metadata_publickey%
            private_key: %saml_metadata_privatekey%
    remote:
        identity_provider:
            enabled: true
            entity_id: %saml_remote_idp_entity_id%
            sso_url: %saml_remote_idp_sso_url%
            certificate: %saml_remote_idp_certificate%

open_conext_engine_block_api_client:
    http_client:
        base_url: %engineblock_api_base_url%
        username: %engineblock_api_username%
        password: %engineblock_api_password%
