---
user: profile
timezone: Europe/Amsterdam
server:
  name: profile.vm.openconext.org
database:
  root_password: root
php:
  packages:
      - php-cli
      - php-bcmath
      - php-mbstring
      - php-mcrypt
      - php-pdo
      - php-pecl-xdebug
      - php-mysql
      - php-gmp
      - php-xml

