---
- name: Install REMI repo
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: Enable REMI repo
  copy: src=remi.repo dest=/etc/yum.repos.d/remi.repo

- name: Install php5-cli
  sudo: yes
  yum: pkg=php-cli state=present enablerepo=remi

- name: Ensure timezone is set in cli php.ini
  lineinfile: dest=/etc/php.ini regexp='date.timezone =' line='date.timezone = {{ timezone }}'

- name: Install php-fpm
  sudo: yes
  yum: pkg=php-fpm state=present enablerepo=remi

- name: Install PHP Packages
  sudo: yes
  yum: pkg={{ item }} state=present enablerepo=remi
  with_items: php.packages

- name: Create PHP session directory
  shell: mkdir /var/lib/php/session creates=/var/lib/php/session

- name: Configure XDebug
  copy: src=xdebug.ini dest=/etc/php.d/15-xdebug.ini
  notify: Restart php-fpm

- name: Remove known default distro files in /etc/php-fpm.d/
  file: path={{item}} state=absent
  with_items:
  - /etc/php-fpm.d/www.conf

- name: Add group {{ user }}
  group: name={{ user }} state=present

- name: Add user {{ user }}
  user: name={{ user }} group={{ user }} createhome=no state=present

- name: Create PHP session directory for user
  shell: mkdir /var/lib/php/session/{{ user }} && chown {{ user }}:{{ user }} /var/lib/php/session/{{ user }} creates=/var/lib/php/session/{{ user }}

- name: Set execute permissions for PHP session directory
  file: path=/var/lib/php/session mode="o+x"

- name: Configure PHP-FPM
  action: template src='php-fpm-pool.conf.j2' dest='/etc/php-fpm.d/{{ server.name }}.conf' owner=nginx group=nginx
  notify: Restart php-fpm

- name: Configure PHP-FPM to run on boot
  command: chkconfig php-fpm on

