services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    OpenConext\EngineBlockApiClientBundle\Service\:
        resource: '../../Service'

    openconext_eb_api.guzzle:
        class: GuzzleHttp\Client
        arguments:
            - [] # Client options

    OpenConext\EngineBlockApiClientBundle\Http\JsonApiClient:
        arguments:
            - '@openconext_eb_api.guzzle'

    OpenConext\EngineBlockApiClientBundle\Repository\ConsentRepository:

    OpenConext\EngineBlockApiClientBundle\HealthCheck\ApiHealthCheck:
        class:
        arguments:
            - '@OpenConext\EngineBlockApiClientBundle\Repository\ConsentRepository'
        tags:
            - { name: surfnet.monitor.health_check }