---
- name: Add nginx repo
  template: src={{ item }}.j2 dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - nginx.repo.gpgkey
    - nginx.repo

- name: Install nginx
  yum: pkg=nginx state=installed enablerepo=nginx

- name: Remove known default distro files in /etc/nginxconf.d/
  file: path={{item}} state=absent
  with_items:
  - /etc/nginx/conf.d/default.conf
  - /etc/nginx/conf.d/ssl.conf
  - /etc/nginx/conf.d/virtual.conf

- name: Copy nginx config-file
  template: src=profile-dev.j2 dest=/etc/nginx/conf.d/profile.conf

- name: Enable nginx service
  service: name=nginx enabled=yes
  notify:
    - Restart nginx

- name: Add firewall rule for HTTP
  sudo: yes
  firewalld: service=http permanent=true state=enabled
  notify: Reload firewall

- name: Add eth1 interface to firewall
  command: firewall-cmd --zone=public --add-interface=eth1

- name: Start nginx
  service: name=nginx state=started
