---
- name: Add nginx repo
  template: src={{ item }}.j2 dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - nginx.repo.gpgkey
    - nginx.repo

- name: Install nginx
  yum: pkg=nginx state=installed enablerepo=nginx

- name: Remove known default distro files in /etc/nginxconf.d/
  file: path={{item}} state=absent
  with_items:
  - /etc/nginx/conf.d/default.conf
  - /etc/nginx/conf.d/ssl.conf
  - /etc/nginx/conf.d/virtual.conf

- name: Copy nginx config-file
  template: src=profile-dev.j2 dest=/etc/nginx/conf.d/profile.conf

- name: Prepare for copying certificates
  shell: mkdir /etc/nginx/conf.d/ssl && chown nginx:nginx /etc/nginx/conf.d/ssl creates=/etc/nginx/conf.d/ssl

- name: Copy SSL certificate
  copy: src=star.vm.openconext.org.pem dest={{ ssl_cert_path }} owner=nginx group=nginx mode=600

- name: Copy SSL key
  copy: src=star.vm.openconext.org.key dest={{ ssl_key_path }} owner=nginx group=nginx mode=600

- name: Enable nginx service
  service: name=nginx enabled=yes
  notify:
    - Restart nginx

- name: Set firewall rules
  become: yes
  firewalld:
    service: "{{ item.service }}"
    permanent: true
    state: enabled
  with_items:
    - { service: "https" }
    - { service: "http" }

- name: Reload firewall
  shell: systemctl stop firewalld && sleep 5 && systemctl start firewalld

- name: Initialize firewall
  become: yes
  firewalld:
    zone: public
    interface: eth1
    state: enabled

- name: Reload firewall
  shell: systemctl stop firewalld && sleep 5 && systemctl start firewalld

- name: Start nginx
  service: name=nginx state=started
