services:
    profile.controller.introduction:
        class: OpenConext\ProfileBundle\Controller\IntroductionController
        arguments:
            - @templating

    profile.controller.profile:
        class: OpenConext\ProfileBundle\Controller\ProfileController
        arguments:
            - @templating
