services:
    profile.controller.introduction:
        class: OpenConext\ProfileBundle\Controller\IntroductionController
        arguments:
            - @templating
            - @profile.security.guard

    profile.controller.my_profile:
        class: OpenConext\ProfileBundle\Controller\MyProfileController
        arguments:
            - @templating
            - @profile.security.guard

    profile.controller.my_services:
        class: OpenConext\ProfileBundle\Controller\MyServicesController
        arguments:
            - @templating
            - @security.token_storage
            - @profile.service.consent
            - @profile.security.guard

    profile.controller.removal:
        class: OpenConext\ProfileBundle\Controller\RemovalController
        arguments:
            - @templating
            - @profile.security.guard

    profile.controller.saml:
        class: OpenConext\ProfileBundle\Controller\SamlController
        arguments:
            - @surfnet_saml.metadata_factory
