services:
    profile.controller.introduction:
        class: OpenConext\ProfileBundle\Controller\IntroductionController
        arguments:
            - @templating

    profile.controller.my_profile:
        class: OpenConext\ProfileBundle\Controller\MyProfileController
        arguments:
            - @templating

    profile.controller.my_services:
        class: OpenConext\ProfileBundle\Controller\MyServicesController
        arguments:
            - @templating
            - @profile.user.user_provider
            - @profile.service.consent_listing

    profile.controller.removal:
        class: OpenConext\ProfileBundle\Controller\RemovalController
        arguments:
            - @templating

    profile.controller.saml:
        class: OpenConext\ProfileBundle\Controller\SamlController
        arguments:
            - @surfnet_saml.metadata_factory
            - @profile.transaction.state_handler
