services:
    profile.controller.introduction:
        class: OpenConext\ProfileBundle\Controller\IntroductionController
        arguments:
            - @templating

    profile.controller.profile:
        class: OpenConext\ProfileBundle\Controller\ProfileController
        arguments:
            - @templating

    profile.controller.services:
        class: OpenConext\ProfileBundle\Controller\ServicesController
        arguments:
            - @templating
            - @surfnet_saml.saml.attribute_dictionary
            - @security.token_storage
            - @profile.service.consent

    profile.controller.removal:
        class: OpenConext\ProfileBundle\Controller\RemovalController
        arguments:
            - @templating

    profile.controller.saml:
        class: OpenConext\ProfileBundle\Controller\SamlController
        arguments:
            - @surfnet_saml.metadata_factory
