services:
    profile.controller.introduction:
        class: OpenConext\ProfileBundle\Controller\IntroductionController
        arguments:
            - @templating
            - @profile.security.guard
            - @logger

    profile.controller.my_profile:
        class: OpenConext\ProfileBundle\Controller\MyProfileController
        arguments:
            - @profile.service.user
            - @templating
            - @profile.security.guard
            - @logger

    profile.controller.my_services:
        class: OpenConext\ProfileBundle\Controller\MyServicesController
        arguments:
            - @templating
            - @profile.provider.authenticated_user
            - @profile.service.consent_listing
            - @profile.security.guard
            - @logger

    profile.controller.locale:
        class: OpenConext\ProfileBundle\Controller\LocaleController
        arguments:
            - @form.factory
            - @profile.service.user
            - @session.flash_bag
            - @profile.security.guard
            - @logger

    profile.controller.removal:
        class: OpenConext\ProfileBundle\Controller\RemovalController
        arguments:
            - @templating
            - @profile.security.guard
            - @logger

    profile.controller.saml:
        class: OpenConext\ProfileBundle\Controller\SamlController
        arguments:
            - @surfnet_saml.metadata_factory
            - @logger
