profile.introduction_overview:
    path:   /
    defaults: { _controller: profile.controller.introduction:overviewAction }

profile.profile_overview:
    path:     /profile
    defaults: { _controller: profile.controller.profile:overviewAction }

profile.services_overview:
    path:     /services
    defaults: { _controller: profile.controller.services:overviewAction }

profile.removal_overview:
    path:     /removal
    defaults: { _controller: profile.controller.removal:overviewAction }

profile.saml_consume_assertion:
    path: /authentication/consume-assertion
    defaults: { _controller: profile.controller.saml:consumeAssertionAction }

profile.saml_metadata:
    path: /authentication/metadata
    defaults: { _controller: profile.controller.saml:metadataAction }

profile.locale_switch_locale:
    path:     /switch-locale
    methods:  [POST]
    defaults: { _controller: OpenConextProfileBundle:Locale:switchLocale }
    requirements:
        'return-url': '.+'
