profile.introduction_overview:
    path:       /
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.introduction:overviewAction

profile.my_profile_overview:
    path:       /my-profile
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.my_profile:overviewAction

profile.my_surf_conext_overview:
    path:       /my-surfconext
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.my_surf_conext:overviewAction

profile.my_services_overview:
    path:       /my-services
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.my_services:overviewAction

profile.my_connections_overview:
    path:       /my-connections
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.my_connections:overviewAction

profile.saml_consume_assertion:
    path:       /authentication/consume-assertion
    methods:    [POST]
    schemes:    https
    defaults:
        _controller: profile.controller.saml:consumeAssertionAction

profile.saml_metadata:
    path:       /authentication/metadata
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.saml:metadataAction

profile.attribute_support_overview:
    path:       /attribute-support
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.attribute_support:overviewAction

profile.attribute_support_confirm_mail_sent:
    path:       /attribute-support/confirmation
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.attribute_support:confirmMailSentAction

profile.attribute_support_send_mail:
    path:       /attribute-support/send-mail
    methods:    [POST]
    schemes:    https
    defaults:
        _controller: profile.controller.attribute_support:sendMailAction

profile.information_request_overview:
    path:       /information-request
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.information_request:overviewAction

profile.information_request_confirm_mail_sent:
    path:       /information-request/confirmation
    methods:    [GET]
    schemes:    https
    defaults:
        _controller: profile.controller.information_request:confirmMailSentAction

profile.information_request_send_mail:
    path:       /information-request/send-mail
    methods:    [POST]
    schemes:    https
    defaults:
        _controller: profile.controller.information_request:sendMailAction

profile.locale_switch_locale:
    path:       /switch-locale
    methods:    [POST]
    schemes:    https
    defaults:
        _controller: profile.controller.locale:switchLocaleAction
    requirements:
        'return-url': '.+'
