profile.profile_overview:
    path:     /
    defaults: { _controller: OpenConextProfileBundle:Profile:overview }

profile.services_overview:
    path:     /services
    defaults: { _controller: OpenConextProfileBundle:Services:overview }

profile.exit_overview:
    path:     /exit
    defaults: { _controller: OpenConextProfileBundle:Exit:overview }

profile.saml_consume_assertion:
    path: /authentication/consume-assertion
    defaults: { _controller: OpenConextProfileBundle:Saml:consumeAssertion }

profile.saml_metadata:
    path: /authentication/metadata
    defaults: { _controller: OpenConextProfileBundle:Saml:metadata }

profile.locale_switch_locale:
    path:     /switch-locale
    methods:  [POST]
    defaults: { _controller: OpenConextProfileBundle:Locale:switchLocale }
    requirements:
        'return-url': '.+'
