profile.introduction_overview:
    path:       /
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\IntroductionController::overview

profile.my_profile_overview:
    path:       /my-profile
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\MyProfileController::overview

profile.my_surf_conext_overview:
    path:       /my-surfconext
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\MySurfConextController::overview

profile.my_surf_conext_user_data_download:
    path:       /my-surfconext/download
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\MySurfConextController::userDataDownload

profile.my_services_overview:
    path:       /my-services
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\MyServicesController::overview

profile.my_services_delete:
    path:       /my-services/delete/{serviceEntityId}
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\MyServicesController::delete
    requirements:
        serviceEntityId: .+

profile.my_connections_overview:
    path:       /my-connections
    methods:    [GET,POST]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\MyConnectionsController::overview

profile.saml_consume_assertion:
    path:       /authentication/consume-assertion
    methods:    [POST]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\SamlController::consumeAssertion

profile.saml_metadata:
    path:       /authentication/metadata
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\SamlController::metadata

profile.attribute_support_overview:
    path:       /attribute-support
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\AttributeSupportController::overview

profile.attribute_support_confirm_mail_sent:
    path:       /attribute-support/confirmation
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\AttributeSupportController::confirmMailSent

profile.attribute_support_send_mail:
    path:       /attribute-support/send-mail
    methods:    [POST]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\AttributeSupportController::sendMail

profile.information_request_overview:
    path:       /information-request
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\InformationRequestController::overview

profile.information_request_confirm_mail_sent:
    path:       /information-request/confirmation
    methods:    [GET]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\InformationRequestController::confirmMailSent

profile.information_request_send_mail:
    path:       /information-request/send-mail
    methods:    [POST]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\InformationRequestController::sendMail

profile.locale_switch_locale:
    path:       /switch-locale
    methods:    [POST]
    schemes:    https
    controller: OpenConext\ProfileBundle\Controller\LocaleController::switchLocale
    requirements:
        return-url: .+
