profile.introduction_overview:
    path:       /
    methods:    [GET]
    defaults:
        _controller: OpenConextProfileBundle:Introduction:overview

profile.profile_overview:
    path:       /profile
    methods:    [GET]
    defaults: 
        _controller: OpenConextProfileBundle:Profile:overview

profile.services_overview:
    path:       /services
    methods:    [GET]
    defaults: 
        _controller: OpenConextProfileBundle:Services:overview

profile.removal_overview:
    path:       /exit
    methods:    [GET]
    defaults: 
        _controller: OpenConextProfileBundle:Removal:overview

profile.saml_consume_assertion:
    path:       /authentication/consume-assertion
    methods:    [POST]
    defaults:
        _controller: OpenConextProfileBundle:Saml:consumeAssertion

profile.saml_metadata:
    path:       /authentication/metadata
    methods:    [GET]
    defaults: 
        _controller: OpenConextProfileBundle:Saml:metadata

profile.locale_switch_locale:
    path:       /switch-locale
    methods:    [POST]
    defaults: 
        _controller: OpenConextProfileBundle:Locale:switchLocale
    requirements:
        'return-url': '.+'
