profile.introduction_overview:
    path:       /
    methods:    [GET]
    defaults:
        _controller: profile.controller.introduction:overviewAction

profile.my_profile_overview:
    path:       /my-profile
    methods:    [GET]
    defaults:
        _controller: profile.controller.my_profile:overviewAction

profile.my_services_overview:
    path:       /my-services
    methods:    [GET]
    defaults:
        _controller: profile.controller.my_services:overviewAction

profile.removal_overview:
    path:       /removal
    methods:    [GET]
    defaults:
        _controller: profile.controller.removal:overviewAction

profile.saml_consume_assertion:
    path:       /authentication/consume-assertion
    methods:    [POST]
    defaults:
        _controller: profile.controller.saml:consumeAssertionAction

profile.saml_metadata:
    path:       /authentication/metadata
    methods:    [GET]
    defaults:
        _controller: profile.controller.saml:metadataAction

profile.saml_retry_transaction:
    path:       /saml/retry-transaction
    methods:    [POST]
    defaults:
        _controller: profile.controller.saml:retryTransactionAction

profile.locale_switch_locale:
    path:       /switch-locale
    methods:    [POST]
    defaults:
        _controller: OpenConextProfileBundle:Locale:switchLocale
    requirements:
        'return-url': '.+'
