services:

    profile.locale_listener:
        class: OpenConext\ProfileBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    profile.form.switch_locale:
        class: OpenConext\ProfileBundle\Form\Type\SwitchLocaleType
        arguments:
            - @router
        tags:
            - { name: form.type, alias: profile_switch_locale }

    profile.twig.locale_extension:
        class: OpenConext\ProfileBundle\Twig\LocaleExtension
        arguments: [ @form.factory ]
        tags:
            - { name: twig.extension }

    profile.twig.transaction_extension:
        class: OpenConext\ProfileBundle\Twig\TransactionExtension
        arguments: [ @form.factory ]
        tags:
            - { name: twig.extension }

    profile.form.retry_transaction:
        class: OpenConext\ProfileBundle\Form\Type\RetryTransactionType
        arguments:
            - @router
        tags:
            - { name: form.type, alias: profile_retry_transaction }


    profile.global_view_parameters:
        class: OpenConext\ProfileBundle\Service\GlobalViewParameters
        arguments:
            - @translator
            - %locales%
            - %help_url%
            - %platform_url%
            - %terms_of_service_url%

    profile.security.authentication.provider:
        class: OpenConext\ProfileBundle\Security\Authentication\Provider\SamlProvider
        arguments:
            - @surfnet_saml.saml.attribute_dictionary

    profile.security.authentication.listener:
        class: OpenConext\ProfileBundle\Security\Firewall\SamlListener
        arguments:
            - @session
            - @security.token_storage
            - @security.authentication.manager
            - @profile.security.authentication.saml
            - @profile.saml.state_handler
            - @profile.transaction.state_handler
            - @logger
            - @twig
            - @form.factory
            - @router

    profile.security.authentication.saml:
        public: false
        class: OpenConext\ProfileBundle\Security\Authentication\SamlInteractionProvider
        arguments:
            - @surfnet_saml.hosted.service_provider
            - @surfnet_saml.remote.idp
            - @surfnet_saml.http.redirect_binding
            - @surfnet_saml.http.post_binding
            - @profile.saml.state_handler

    profile.saml.state_handler:
        public: false
        class: OpenConext\ProfileBundle\Saml\StateHandler
        arguments:
            - @profile.session

    profile.transaction.state_handler:
        public: false
        class: OpenConext\ProfileBundle\Transaction\StateHandler
        arguments:
            - @profile.session
            - %open_conext_profile_allowed_transaction_attempts%

    profile.session:
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: ['@session', 'getBag']
        arguments: ['profile']

    profile.session.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__profile__'
            - '/'
        calls:
            - [setName, ['profile']]

    profile.service.consent:
        class: OpenConext\ProfileBundle\Service\ConsentService
        arguments:
            - @logger
            - @openconext_eb_api.repository.consent
            - @saml.attribute.surfconext.id

    profile.user.user_provider:
        class: OpenConext\ProfileBundle\User\UserProvider
        arguments:
            - @security.token_storage

    profile.service.consent_listing:
        class: OpenConext\ProfileBundle\Service\SpecifiedConsentListService
        arguments:
            - @profile.service.consent
            - @profile.consent.blacklist_filter

    profile.consent.blacklist_filter:
        class: OpenConext\ProfileBundle\Consent\BlacklistFilter
