services:
    profile.engine_block_entity_id:
        public: false
        class: OpenConext\Profile\Value\EntityId
        arguments:
            - ~ # engine block entity id

    profile.storage.locale_cookie:
        class: OpenConext\ProfileBundle\Storage\SingleCookieStorage
        arguments:
            - ~ # locale cookie domain
            - ~ # locale cookie key
            - ~ # locale cookie expiration date
            - ~ # locale cookie secure
            - ~ # locale cookie http only
        tags:
            - { name: kernel.event_subscriber }

    profile.attribute_support.email_from:
        public: false
        class: OpenConext\Profile\Value\EmailAddress
        arguments:
            - ~ # attribute support email from

    profile.attribute_support.email_to:
        public: false
        class: OpenConext\Profile\Value\EmailAddress
        arguments:
            - ~ # attribute support email to

    profile.security.guard:
        public: false
        class: OpenConext\ProfileBundle\Security\Guard
        arguments:
            - @security.authorization_checker

    profile.locale_listener:
        class: OpenConext\ProfileBundle\EventListener\LocaleListener
        arguments:
            - @profile.service.locale
        tags:
            - { name: kernel.event_subscriber }

    profile.form.switch_locale:
        class: OpenConext\ProfileBundle\Form\Type\SwitchLocaleType
        arguments:
            - @router
            - @profile.service.locale
        tags:
            - { name: form.type, alias: profile_switch_locale }

    profile.form.attribute_support_mail:
        class: OpenConext\ProfileBundle\Form\Type\AttributeSupportMailType
        arguments:
            - @router
        tags:
            - { name: form.type, alias: profile_attribute_support_mail }

    profile.form.information_request_mail:
        class: OpenConext\ProfileBundle\Form\Type\InformationRequestMailType
        arguments:
            - @router
        tags:
            - { name: form.type, alias: profile_information_request_mail }

    profile.twig.locale_extension:
        public: false
        class: OpenConext\ProfileBundle\Twig\LocaleExtension
        arguments: [ @form.factory ]
        tags:
            - { name: twig.extension }

    profile.global_view_parameters:
        public: false
        class: OpenConext\ProfileBundle\Service\GlobalViewParameters
        arguments:
            - @translator
            - %locales%
            - %help_url%
            - %platform_url%
            - %terms_of_service_url%
            - %profile_explanation_image_path%
            - %attribute_information_url%

    profile.security.authentication.provider:
        public: false
        class: OpenConext\ProfileBundle\Security\Authentication\Provider\SamlProvider
        arguments:
            - @surfnet_saml.saml.attribute_dictionary

    profile.security.authentication.listener:
        public: false
        class: OpenConext\ProfileBundle\Security\Firewall\SamlListener
        arguments:
            - @session
            - @security.token_storage
            - @security.authentication.manager
            - @profile.security.authentication.saml
            - @profile.saml.state_handler
            - @logger
            - @twig

    profile.security.authentication.saml:
        public: false
        class: OpenConext\ProfileBundle\Security\Authentication\SamlInteractionProvider
        arguments:
            - @surfnet_saml.hosted.service_provider
            - @surfnet_saml.remote.idp
            - @surfnet_saml.http.redirect_binding
            - @surfnet_saml.http.post_binding
            - @profile.saml.state_handler

    profile.saml.state_handler:
        public: false
        class: OpenConext\ProfileBundle\Saml\StateHandler
        arguments:
            - @profile.session

    profile.saml_session:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: ['@session', 'getBag']
        arguments: ['profile_saml']

    profile.saml_session.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__profile_saml__'
        calls:
            - [setName, ['profile_saml']]

    profile.session:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        factory: ['@session', 'getBag']
        arguments: ['profile']

    profile.session.namespaced_attribute_bag:
        public: false
        class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag
        arguments:
            - '__profile__'
        calls:
            - [setName, ['profile']]

    profile.service.attribute_support_mail:
        public: false
        class: OpenConext\ProfileBundle\Service\AttributeSupportMailService
        arguments:
            - @profile.attribute_support.email_from
            - @profile.attribute_support.email_to
            - @mailer
            - @templating
            - @profile.service.user

    profile.service.locale:
        public: false
        class: OpenConext\ProfileBundle\Service\LocaleService
        arguments:
            - @profile.repository.locale
            - @profile.available_locales
            - @profile.default_locale

    profile.available_locales:
        public: false
        class: OpenConext\Profile\Value\LocaleSet
        factory: [OpenConext\Profile\Value\LocaleSet, create]
        arguments:
            - [] # available locales

    profile.default_locale:
        public: false
        class: OpenConext\Profile\Value\Locale
        arguments:
            - ~ # default locale

    profile.locale_storage_driver:
        public: false
        class: OpenConext\ProfileBundle\Service\LocaleStorageDriver
        arguments:
            - @profile.storage.locale_cookie

    profile.repository.locale:
        public: false
        class: OpenConext\ProfileBundle\Profile\Repository\LocaleRepository
        arguments:
            - @profile.locale_storage_driver

    profile.repository.user:
        public: false
        class: OpenConext\ProfileBundle\Profile\Repository\UserRepository
        arguments:
            - @profile.session.namespaced_attribute_bag

    profile.provider.authenticated_user:
        public: false
        class: OpenConext\ProfileBundle\Service\AuthenticatedUserProvider
        arguments:
            - @security.token_storage

    profile.service.user:
        public: false
        class: OpenConext\ProfileBundle\Service\UserService
        arguments:
            - @profile.service.support_contact_email
            - @profile.repository.user
            - @profile.provider.authenticated_user
            - @profile.service.locale
            - @profile.engine_block_entity_id

    profile.service.consent:
        public: false
        class: OpenConext\ProfileBundle\Service\ConsentService
        arguments:
            - @logger
            - @openconext_eb_api.repository.consent
            - @saml.attribute.surfconext.id

    profile.service.consent_listing:
        public: false
        class: OpenConext\ProfileBundle\Service\SpecifiedConsentListService
        arguments:
            - @profile.service.consent
            - @openconext_eb_api.service.attribute_release_policy

    profile.service.support_contact_email:
        public: false
        class: OpenConext\ProfileBundle\Service\SupportContactEmailService
        arguments:
            - @openconext_eb_api.repository.support_contact_information

    profile.service.attribute_filter:
        public: false
        class: OpenConext\ProfileBundle\Attribute\AttributeFilter