name: Build docker container for the SP Dashboard

on:
  release:
    types: [ published ]
  workflow_dispatch:
  push:
    branches: [ feature/github_actions_build_docker ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build the php-fpm container and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile
        tag_with_ref: true
        push: true
        target: phpfpm-build
        tags: ghcr.io/openconext/openconext-profile/profile_php-fpm:latest
