name: tag-release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      COMPONENT_NAME: OpenConext-profile
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: OpenConext/Stepup-Build
      - name: Output the semver tag to the tag variable
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Run release script
        run: ./stepup-build.sh ${COMPONENT_NAME} --tag ${{ steps.vars.outputs.tag }}
      - name: Grab the archive filename
        id: archive
        run: |
          echo "archive=$(find . -maxdepth 1 -name "$COMPONENT_NAME*.tar.bz2" -printf '%f\n')" >> $GITHUB_OUTPUT
          echo "shasum=$(find . -maxdepth 1 -name "$COMPONENT_NAME*.sha" -printf '%f\n')" >> $GITHUB_OUTPUT
      - name: Build Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          default-commit-type: New Features

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ steps.archive.outputs.archive }}
            ${{ steps.archive.outputs.shasum }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          body: ${{ steps.changelog.outputs.changelog }}

  after_build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker container build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-push-docker-image.yml
